### ISSUE TITLE
"low hanging" improvements to dot output

### ISSUE THREAD

**Issue by dlehavi-resonai** [resonai/ybt#106]
Two suggestions (which a: I think are easy, and b: are related to the graph queries):
- color cached nodes with some color
- color boundaries of nodes by target type.
- put stuff whose only dependencies is build environments in rectangular boxes (this means that we have to "decorate" build environments in the YBuilds; I'm not sure if this is good from a very platonic POV this is wrong, but may be rather useful for other things too)

**Comment by itamaro** [comment]
hurray onboarding task ^_^

**Comment by dlehavi-resonai** [comment]
closed on PR #120
