### ISSUE TITLE
building a 3rd party

### ISSUE THREAD

**Issue by aviresonai** [resonai/ybt#114]
I want to be able to run build of a 3rd party I am using (as part of the base image) without running all the base image build

**Comment by itamaro** [comment]
1. can you explain the use case? (what are you trying to get)
2. can you provide an example where this would be useful?
3. if you define a simple `DockerImage` target that starts from a simple base image and defines just the 3rd party you're interested in as a dependency, would it give you what you want?

**Comment by aviresonai** [comment]
I was trying to replace the grpc version and looking for a way to test that without rebuilding the whole base image
the DockerImage work around sounds a valid solution so I am closing this issue
