### ISSUE TITLE
Missing test-runner features

### ISSUE THREAD

**Issue by itamaro** [resonai/ybt#48]
- [x] Retry flaky tests N times
- [x] Collect stats and print report at the end
- [x] Support both "fail fast" (exit on first failure) and run all tests (don't exit on first failure) modes

**Comment by dlehavi-resonai** [comment]
aren't two of these already closed by @bergden-resonai  ?

**Comment by itamaro** [comment]
> aren't two of these already closed by @bergden-resonai ?

yap. marked.
