### ISSUE TITLE
copy_generated_to of proto builder shouldn't delete before coping

### ISSUE THREAD

**Issue by eyal-resonai** [resonai/ybt#98]
Current state is that what we have in the target dir of the copy_generated_to is a random set of protos of the last ybt build.
There are two cases where the copy_generated_to feature is useful:
1. IDEs which can be configured to do complications
2. development env in some image in which you want to run scripts which needs the proto output (a.k.a ywzrun)

In both cases the feature is useless if it hold the protos of the last run and it is perfectly OK to have stale generated files in cases you've changed the proto and didn't build since then.

 @itamaro Is there any reason not to change it so that copy_generated_to just copy without deleting?

**Comment by itamaro** [comment]
IIRC the reason for deleting before copying was to avoid situation where proto's that were moved/renamed/deleted still have their generated outputs under build/gen.

If this is no longer a concern, then I think it's ok to change the behavior.

**Comment by dlehavi-resonai** [comment]
Please see the new issue reported, it may be a dup, but there is a suggestion there
